### ISSUE TITLE
提供的二进制中游戏标题似乎有误？

### ISSUE THREAD

**Issue by zephray** [mikukonai/PSP-2048#1]
如图

![default](https://user-images.githubusercontent.com/5101637/53292974-96bcf280-3799-11e9-90e4-580c1ed708cf.png)

**Comment by mikukonai** [comment]
因为这个2048是基于示例修改的_(:з」∠)_ 是在按键摇杆示例的基础上修改的，应该是配置文件哪里没有看到，就打包进去了_(:з」∠)_

**Comment by zephray** [comment]
嗯）我这也没有PSP开发环境没法帮忙重新编译了
